### ISSUE TITLE
jaguar_serializer not compatible with jaguar_http_cli

### ISSUE THREAD

**Issue by rafalbednarczuk** [Jaguar-dart/jaguar_serializer#110]
I use the newest version of jaguar_http_cli in order to make request.
If I want to use jaguar_serializer to my project there are conflicts in dependencies.
pubspec.yaml for jaguar_http_cli only using with flutter:
```
name: balloonstour
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  flutter_redux: "^0.5.0"
  jaguar_http_cli: "^0.0.2+1"

dev_dependencies:

  http: "^0.11.3"
  meta: "^1.1.0"

jaguar_http:
  - lib/example.dart

```
flutter project only jaguar_serializer pubspec.yaml
```
name: jaguar_serializer_test
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  jaguar_serializer: ^1.0.0-dev1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.0
  jaguar_serializer_cli: ^1.0.0-dev1

flutter:
  uses-material-design: true
```
Combined in one project: 
```
name: balloonstour
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_redux: "^0.5.0"
  jaguar_http_cli: "^0.0.2+1"
  jaguar_serializer: ^1.0.0-dev1

dev_dependencies:

  http: "^0.11.3"
  meta: "^1.1.0"
  build_runner: ^0.8.0
  jaguar_serializer_cli: ^1.0.0-dev1

flutter:

jaguar_http:
  - lib/example.dart

```
If I run packages get I get:
Because jaguar_http_cli 0.0.2+1 depends on build_runner ^0.6.0 and no versions of jaguar_http_cli match >0.0.2+1 <0.1.0, jaguar_http_cli ^0.0.2+1 requires build_runner ^0.6.0.
So, because balloonstour depends on both jaguar_http_cli ^0.0.2+1 and build_runner ^0.8.0, version solving failed.
pub get failed (1)
